
ERROR - log_manager - error_logger - 24168 - 140540079265536 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 13:01:42,911
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 497, in search
    if 'show_short_version' in es_params.keys():
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 497, in search
    if 'show_short_version' in es_params.keys():
  File "/home/eha/anaconda2/envs/texta/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/eha/anaconda2/envs/texta/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit

ERROR - log_manager - error_logger - 24708 - 140484343318272 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 13:09:06,669
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 461, in search
    import pdb;pdb.set_trace()
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 461, in search
    import pdb;pdb.set_trace()
  File "/home/eha/anaconda2/envs/texta/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/eha/anaconda2/envs/texta/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit

ERROR - log_manager - error_logger - 27695 - 140303102506752 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 13:58:00,818
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 504, in search
    if(u'[HL]' in highlight_data[0]['category']):
IndexError: list index out of range

ERROR - log_manager - error_logger - 27766 - 139895538538240 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 13:58:52,666
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 504, in search
    if(u'[HL]' in highlight_data[0]['category']):
IndexError: list index out of range

ERROR - log_manager - error_logger - 27818 - 140402131687168 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:00:09,773
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    print(datum['spans'], 'DATUM SPANS')
UnboundLocalError: local variable 'datum' referenced before assignment

ERROR - log_manager - error_logger - 27842 - 139710257792768 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:00:26,262
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    print(highlight_data['spans'], 'HL SPANS')
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 28043 - 140331654682368 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:02:04,576
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    print([x['spans'] for i in highlight_data], 'HL SPANS')
NameError: global name 'x' is not defined

ERROR - log_manager - error_logger - 28184 - 140392436827904 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:03:33,409
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    print('\n' + [x['spans'] for x in highlight_data], 'HL SPANS')
TypeError: cannot concatenate 'str' and 'list' objects

ERROR - log_manager - error_logger - 29010 - 140154850174720 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:20:09,778
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 514, in search
    print(out['column_names']['text.text'])
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 29213 - 140147169322752 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:23:14,280
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 514, in search
    print(hit['highlight']['text.text'][0])
KeyError: 'text.text'

ERROR - log_manager - error_logger - 29234 - 140544018056960 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:23:26,922
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 514, in search
    print(hit['highlight'][u'text.text'][0])
KeyError: u'text.text'

ERROR - log_manager - error_logger - 29270 - 140457200326400 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:23:38,032
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 515, in search
    print(hit['highlight'][u'text.text'][0])
KeyError: u'text.text'

ERROR - log_manager - error_logger - 29344 - 139698617554688 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:25:19,902
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 516, in search
    print(hit['highlight'][u'text.text'][0])
KeyError: u'text.text'

ERROR - log_manager - error_logger - 29344 - 139698617554688 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:25:19,981
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 516, in search
    print(hit['highlight'][u'text.text'][0])
KeyError: u'text.text'

ERROR - log_manager - error_logger - 29375 - 139736304281344 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:25:35,295
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    print(hit['highlight'][u'text.text'][0])
KeyError: u'text.text'

ERROR - log_manager - error_logger - 29512 - 140066913519360 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:27:06,085
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    print(hit['_source']['text'][0])
KeyError: 0

ERROR - log_manager - error_logger - 29512 - 140066913519360 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:27:22,130
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    print(hit['_source']['text'][0])
KeyError: 0

ERROR - log_manager - error_logger - 29693 - 139763016128256 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:30:01,930
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 513, in search
    print(hit['_source']['text'].decode('utf8'), 'TEXT') #({u'lang': u'ru', u'text': u'rutexthere'
AttributeError: 'dict' object has no attribute 'decode'

ERROR - log_manager - error_logger - 29719 - 139624416249600 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-07 14:30:23,322
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 513, in search
    print(hit['_source']['text']['text'].decode('utf8'), 'TEXT') #({u'lang': u'ru', u'text': u'rutexthere'
  File "/home/eha/anaconda2/envs/texta/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

ERROR - log_manager - error_logger - 3285 - 139777396557568 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:02:47,385
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 504, in search
    import pdb;pdb.set_trace()
KeyError: u'text.text'

ERROR - log_manager - error_logger - 3518 - 139645663450880 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:06:03,100
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    if(highlight_data != []):
UnboundLocalError: local variable 'content2' referenced before assignment

ERROR - log_manager - error_logger - 3518 - 139645663450880 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:06:17,060
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    if(highlight_data != []):
UnboundLocalError: local variable 'content2' referenced before assignment

ERROR - log_manager - error_logger - 3518 - 139645663450880 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:06:25,644
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    if(highlight_data != []):
UnboundLocalError: local variable 'content2' referenced before assignment

ERROR - log_manager - error_logger - 3707 - 139954086090496 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:08:18,538
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    if(highlight_data != []):
UnboundLocalError: local variable 'content2' referenced before assignment

ERROR - log_manager - error_logger - 3835 - 140151682987776 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:09:15,572
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 504, in search
    import pdb;pdb.set_trace()
UnboundLocalError: local variable 'content2' referenced before assignment

ERROR - log_manager - error_logger - 3835 - 140151691380480 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:09:20,172
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 504, in search
    import pdb;pdb.set_trace()
UnboundLocalError: local variable 'content2' referenced before assignment

ERROR - log_manager - error_logger - 3906 - 140365835765504 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:10:35,692
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 504, in search
    import pdb;pdb.set_trace()
UnboundLocalError: local variable 'content2' referenced before assignment

ERROR - log_manager - error_logger - 4105 - 139647593350912 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:13:15,477
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    if(highlight_data != []):
IndexError: list assignment index out of range

ERROR - log_manager - error_logger - 4209 - 140367974323968 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:14:20,045
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 505, in search
    if(highlight_data != []):
IndexError: list assignment index out of range

ERROR - log_manager - error_logger - 5126 - 139933363312384 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 11:28:33,574
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    if 'show_short_version' in es_params.keys():
IndexError: list assignment index out of range

ERROR - log_manager - error_logger - 11815 - 140410300012288 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:02:31,921
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 520, in search
    transliterate_highlight_spans([x['spans'] for x in highlight_data], hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 2, in transliterate_highlight_spans
    query_span = [x['spans'] for x in highlight_data]
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 11881 - 140520014874368 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:04:00,810
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 520, in search
    transliterate_highlight_spans([x['spans'] for x in highlight_data], hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 2, in transliterate_highlight_spans
    query_span = [x['spans'] for x in highlight_data]
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 11881 - 140520023791360 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:04:00,828
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 520, in search
    transliterate_highlight_spans([x['spans'] for x in highlight_data], hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 2, in transliterate_highlight_spans
    query_span = [x['spans'] for x in highlight_data]
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 11916 - 139739046971136 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:04:19,786
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 520, in search
    transliterate_highlight_spans([x['spans'] for x in highlight_data], hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 2, in transliterate_highlight_spans
    query_span = [x['spans'] for x in highlight_data]
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 11916 - 139739037792000 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:04:19,798
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 520, in search
    transliterate_highlight_spans([x['spans'] for x in highlight_data], hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 2, in transliterate_highlight_spans
    query_span = [x['spans'] for x in highlight_data]
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 11987 - 140140192044800 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:05:07,128
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 520, in search
    transliterate_highlight_spans([x['spans'] for x in highlight_data], hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 2, in transliterate_highlight_spans
    query_span = [x['spans'] for x in highlight_data]
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 12017 - 139773332129536 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:05:22,311
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    transliterate_highlight_spans([x['spans'] for x in highlight_data], hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 2, in transliterate_highlight_spans
    query_span = [x['spans'] for x in highlight_data]
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 12086 - 139800373384960 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:06:06,059
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    transliterate_highlight_spans(highlight_data, hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 13, in transliterate_highlight_spans
    for span in query_span['spans']:
TypeError: list indices must be integers, not str

ERROR - log_manager - error_logger - 12196 - 139931330139904 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:08:19,948
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    transliterate_highlight_spans(highlight_data, hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 17, in transliterate_highlight_spans
    fact_words = source_text[span[0]:span[1]].split(' ')
TypeError: 'int' object has no attribute '__getitem__'

ERROR - log_manager - error_logger - 12256 - 140495672051456 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:08:52,915
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    transliterate_highlight_spans(highlight_data, hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 18, in transliterate_highlight_spans
    fact_words = source_text[span[0]:span[1]].split(' ')
TypeError: 'int' object has no attribute '__getitem__'

ERROR - log_manager - error_logger - 12285 - 140441766074112 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:09:12,852
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    transliterate_highlight_spans(highlight_data, hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 19, in transliterate_highlight_spans
    fact_words = source_text[span[0]:span[1]].split(' ')
TypeError: 'int' object has no attribute '__getitem__'

ERROR - log_manager - error_logger - 12422 - 140346305304320 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:10:54,247
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    transliterate_highlight_spans(highlight_data, hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 15, in transliterate_highlight_spans
    fact_words = source_text[span[0]:span[1]].split(' ')
NameError: global name 'span' is not defined

ERROR - log_manager - error_logger - 12491 - 140042248218368 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:11:22,427
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 519, in search
    transliterate_highlight_spans(highlight_data, hit['_source']['text']['translit'], hit['_source']['text']['text'])
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 28, in transliterate_highlight_spans
    dict_val[spans] = [translit_facts_spans]
NameError: global name 'spans' is not defined

ERROR - log_manager - error_logger - 13178 - 140308698765056 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:19:07,685
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 522, in search
    tagged_text=content)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/utils/highlighter.py", line 51, in highlight
    spans_to_tags = self._get_tags_for_text_index(tagged_text, alignment, highlight_data)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/utils/highlighter.py", line 147, in _get_tags_for_text_index
    for text_index in range(*span):
TypeError: range() argument after * must be an iterable, not int

ERROR - log_manager - error_logger - 13449 - 140235791492864 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 13:22:23,986
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 524, in search
    tagged_text=content)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/utils/highlighter.py", line 51, in highlight
    spans_to_tags = self._get_tags_for_text_index(tagged_text, alignment, highlight_data)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/utils/highlighter.py", line 147, in _get_tags_for_text_index
    for text_index in range(*span):
TypeError: range() argument after * must be an iterable, not int

ERROR - log_manager - error_logger - 16645 - 140702367827712 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 14:06:30,959
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 428, in search
    row = collections.OrderedDict([(x, '') for x in out['column_names']]) # OrderedDict to remember column names with their content
NameError: global name 'collections' is not defined

ERROR - log_manager - error_logger - 16645 - 140702367827712 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 14:06:30,978
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 428, in search
    row = collections.OrderedDict([(x, '') for x in out['column_names']]) # OrderedDict to remember column names with their content
NameError: global name 'collections' is not defined

ERROR - log_manager - error_logger - 20476 - 140631330350848 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 14:57:42,747
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 513, in search
    row = highlight_transliterately(col, row, highlight_data, content, hit)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 68, in highlight_transliterately
    row['text.translit'].append(content_hl_trans)
AttributeError: 'str' object has no attribute 'append'

ERROR - log_manager - error_logger - 23790 - 139980069037824 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 15:45:00,419
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 509, in search
    row = highlight_transliterately(col, row, highlight_data, content, hit)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 86, in highlight_transliterately
    for hl_col in hl_cols.remove(col):
TypeError: 'NoneType' object is not iterable

ERROR - log_manager - error_logger - 23852 - 139993233401600 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 15:46:10,553
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 509, in search
    row = highlight_transliterately(col, row, highlight_data, content, hit)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 87, in highlight_transliterately
    for hl_col in hl_cols.remove(col):
TypeError: 'NoneType' object is not iterable

ERROR - log_manager - error_logger - 24099 - 140182655305472 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 15:49:47,307
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 509, in search
    row = highlight_transliterately(col, row, highlight_data, content, hit)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 87, in highlight_transliterately
    for hl_col in hl_cols.remove(col):
TypeError: 'NoneType' object is not iterable

ERROR - log_manager - error_logger - 24168 - 140350641018624 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 15:50:05,901
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 509, in search
    row = highlight_transliterately(col, row, highlight_data, content, hit)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 86, in highlight_transliterately
    for hl_col in hl_cols.remove(col):
TypeError: 'NoneType' object is not iterable

ERROR - log_manager - error_logger - 24253 - 140331361240832 - {"process": "SEARCH CORPUS", "context": {"user_name": "ranet"}, "event": "documents_queried_failed", "module": "searcher.views"} - 2018-03-08 15:51:28,483
Traceback (most recent call last):
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/views.py", line 509, in search
    row = highlight_transliterately(col, row, highlight_data, content, hit)
  File "/home/eha/Desktop/texta/texta-ekt-polishing-dev/searcher/view_functions/tranlist_highlighting.py", line 88, in highlight_transliterately
    col_name = col.split('.'[1])
IndexError: string index out of range
